male(Shantanu).
male(Bheeshma).
male(Chitrangada).
male(Vichitravirya).
male(Shalva).
male(Drupada).
male(Vyasa).
male(Dhritarashtra).
male(Pandu).
male(Vidur).
male(Krishna).
male(Shakuni).
male(Dharma).
male(Vayu).
male(Indra).
male(Yudishthira).
male(Bhima).
male(Arjun).
male(Nakul).
male(Sahdev).
male(Karna).
male(Duryodhan).
male(Dushasan).
male(Vikarna).
male(Sukarna).
male(Balram).
male(Drona).
male(Kripa).
male(Ashwatthama).
male(Drupada).
male(Dhrishtadumna).
male(Abhimanyu).
male(Parikshit).
male(Parashara).
male(Surya).
male(Ghatotkacha).
male(Prativindhya).
male(Shatanika).
male(Sutasoma).
male(Shrutasena).
male(Shrutkarma).
male(Vasudeva).
male(Jarasanta).
male(Kansa).
male(Adhirata).
female(Ganga).
female(Satyavati).
female(Amba).
female(Ambika).
female(Ambalika).
female(Kunti).
female(Madri).
female(Gandhari).
female(Draupadi).
female(Subhadra).
female(Kripi).
female(Uttara).
female(Madravati).
female(Hidimba).
female(Bhanumati).
female(Devaki).
female(Radha).
